//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_GP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cpu_info
    {
        public int cpu_id { get; set; }
        public string cpu_Name { get; set; }
        public int cpu_core { get; set; }
        public int cpu_threads { get; set; }
        public decimal cpu_base_frequency { get; set; }
        public decimal cpu_turbo_frequency { get; set; }
        public int cpu_tdp { get; set; }
        public Nullable<int> cpu_brandId { get; set; }
        public Nullable<int> cpu_sockets_id { get; set; }
    
        public virtual brands brands { get; set; }
        public virtual cpu_sockets cpu_sockets { get; set; }
    }
}
