//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_GP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mainboard_info
    {
        public int mainboard_id { get; set; }
        public string mainboard_name { get; set; }
        public string mainboard_sizeType { get; set; }
        public Nullable<int> mainboard_brand { get; set; }
        public Nullable<int> mainboard_sockets_id { get; set; }
    
        public virtual brands brands { get; set; }
        public virtual cpu_sockets cpu_sockets { get; set; }
    }
}
