//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_GP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class powers
    {
        public int powers_id { get; set; }
        public Nullable<int> powers_brands { get; set; }
        public int powers_warts { get; set; }
        public string powers_size { get; set; }
    
        public virtual brands brands { get; set; }
    }
}
