//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_GP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectDBEntities : DbContext
    {
        public ProjectDBEntities()
            : base("name=ProjectDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<brands> brands { get; set; }
        public virtual DbSet<cpu_info> cpu_info { get; set; }
        public virtual DbSet<cpu_sockets> cpu_sockets { get; set; }
        public virtual DbSet<disks> disks { get; set; }
        public virtual DbSet<GPU> GPU { get; set; }
        public virtual DbSet<mainboard_info> mainboard_info { get; set; }
        public virtual DbSet<mem> mem { get; set; }
        public virtual DbSet<powers> powers { get; set; }
        public virtual DbSet<Talk> Talk { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<Hot> Hot { get; set; }
    }
}
